default:
  target: "dev"
  outputs:
    dev:
      type: "snowflake"
      account: "pm98618.ap-south-1.aws"
      user: "KRISHNA_SUDHAMA839"
      role: "KRISHNA_SUDHAMA839_ROLE"
      database: "KRISHNA_SUDHAMA839_DB"
      warehouse: "COMPUTE_WH"
      schema: "Maplemonk"
      threads: 10
      client_session_keep_alive: false
