default:
  target: "dev"
  outputs:
    dev:
      type: "snowflake"
      account: "fs03183.ap-south-1.aws"
      user: "SnitchClothing"
      password: "4MClothingLLP"
      role: "ACCOUNTADMIN"
      database: "snitch_db"
      warehouse: "snitch_wh"
      schema: "MAPLEMONK"
      threads: 10
      client_session_keep_alive: false
