default:
  target: "dev"
  outputs:
    dev:
      type: "snowflake"
      account: "cm76873.ap-south-1.aws"
      user: "analyticsgladful"
      password: "Gladful9!"
      role: "ACCOUNTADMIN"
      database: "GLADFUL_DB"
      warehouse: "GLADFUL_WH"
      schema: "MapleMonk"
      threads: 10
      client_session_keep_alive: false
