default:
  target: "dev"
  outputs:
    dev:
      type: "snowflake"
      account: "ikcmrrt-zb39179"
      user: "bummeranalytics"
      password: "9U7!6pS!i5"
      role: "ACCOUNTADMIN"
      database: "BUMMER_DB"
      warehouse: "BUMMER_WH"
      schema: "MAPLEMONK"
      threads: 10
      client_session_keep_alive: false
