default:
  target: "dev"
  outputs:
    dev:
      type: "snowflake"
      account: "twfdnzl-ta71507"
      user: "rasanalytics"
      password: "LyBXcrQip2xG2TC"
      role: "ACCOUNTADMIN"
      database: "ras_db"
      warehouse: "ras_wh"
      schema: "MAPLEMONK"
      threads: 10
      client_session_keep_alive: false
