default:
  target: "dev"
  outputs:
    dev:
      type: "snowflake"
      account: "ww77149.ap-south-1.aws"
      user: "AAKASH"
      password: "Maplemonk@123"
      role: "ACCOUNTADMIN"
      database: "TCNSDEMO"
      warehouse: "TEST_WH"
      schema: "MAPLEMONK"
      threads: 10
      client_session_keep_alive: false
