default:
  target: "dev"
  outputs:
    dev:
      type: "snowflake"
      account: "ubpetoi-jr09127"
      user: "italiancolony"
      password: "nrWberRdXWE1iry"
      role: "ACCOUNTADMIN"
      database: "italiancolony_db"
      warehouse: "italiancolony_wh"
      schema: "MAPLEMONK"
      threads: 10
      client_session_keep_alive: false
