default:
  target: "dev"
  outputs:
    dev:
      type: "snowflake"
      account: "iw72048.ap-south-1.aws"
      user: "AAKASH"
      role: "ACCOUNTADMIN"
      database: "MM_TEST"
      warehouse: "COMPUTE_WH"
      schema: "UPGRADE_TEST"
      threads: 10
      client_session_keep_alive: false
