default:
  target: "dev"
  outputs:
    dev:
      type: "snowflake"
      account: "tg93861.ap-south-1.aws"
      user: "anveshantech"
      password: "r3FskA{,wv"
      role: "ACCOUNTADMIN"
      database: "ANVESHAN_DB"
      warehouse: "ANVESHAN_WH"
      schema: "MAPLEMONK"
      threads: 10
      client_session_keep_alive: false
