snowflake:
  target: "dev"
  outputs:
    dev:
      type: "snowflake"
      password: "Maplemonk@123"
      role: "ACCOUNTADMIN"
      database: "DEMO_DB"
      warehouse: "COMPUTE_WH"
      schema: "public"
      threads: 10
      client_session_keep_alive: false
