default:
  target: "dev"
  outputs:
    dev:
      type: "snowflake"
      account: "ogboqub-vs80816"
      user: "Indusvalleyanalytics"
      password: "1nBm4gA8hEGSflk"
      role: "ACCOUNTADMIN"
      database: "indusvalley_db"
      warehouse: "indusvalley_wh"
      schema: "MAPLEMONK"
      threads: 10
      client_session_keep_alive: false
