default:
  target: "dev"
  outputs:
    dev:
      type: "snowflake"
      account: "ww77149.ap-south-1.aws"
      user: "AAKASH"
      password: "Maplemonk@123"
      role: "ACCOUNTADMIN"
      database: "MM_TEST"
      warehouse: "COMPUTE_WH"
      schema: "Maplemonk"
      threads: 10
      client_session_keep_alive: false
