default:
  target: "dev"
  outputs:
    dev:
      type: "snowflake"
      account: "fk47959.ap-south-1.aws"
      user: "perforacare"
      password: "5NPZD5pB"
      role: "ACCOUNTADMIN"
      database: "Perfora_DB"
      warehouse: "Perfora_WH"
      schema: "MapleMonk"
      threads: 10
      client_session_keep_alive: false
