default:
  target: "dev"
  outputs:
    dev:
      type: "snowflake"
      account: "ae07636.west-us-2.azure"
      user: "Sastry"
      password: "Snowflake5"
      role: "ACCOUNTADMIN"
      database: "MM_DB"
      warehouse: "MM_DEMO"
      schema: "PUBLIC"
      threads: 10
      client_session_keep_alive: false
