default:
  target: "dev"
  outputs:
    dev:
      type: "snowflake"
      account: "pm98618.ap-south-1.aws"
      user: "HULKTESTER772"
      role: "HULKTESTER772_ROLE"
      database: "HULKTESTER772_DB"
      warehouse: "COMPUTE_WH"
      schema: "Maplemonk"
      threads: 10
      client_session_keep_alive: false
