default:
  target: "dev"
  outputs:
    dev:
      type: "snowflake"
      account: "JR70875.ap-south-1.aws"
      user: "analyticsfemora"
      password: "Femora@123"
      role: "ACCOUNTADMIN"
      database: "MAPLEMONK"
      warehouse: "Femora_WH"
      schema: "MapleMonk"
      threads: 10
      client_session_keep_alive: false
