default:
  target: "dev"
  outputs:
    dev:
      dataset: "maplemonk"
      keyfile_json:
        auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
        auth_uri: "https://accounts.google.com/o/oauth2/auth"
        client_email: "big-query-mm-test@maplemonk-prod.iam.gserviceaccount.com"
        client_id: "111666881847990844486"
        client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/big-query-mm-test%40maplemonk-prod.iam.gserviceaccount.com"
        private_key: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDcivZWNlEE+2Gi\nmwF1yQ24bYD8IQ/WBFphRQT0+/RMOCZU6Lr3PBquzj62Kv+OLgRWx7GlywRMyakK\nGV9xNqBKeOkSeaZ41+Fv/M8LMLFMJJawFbJYuTspemgbWVWIHUrFeU9KBxhm0DC6\na6vN+94x7Kxo/ccIwA534k2eQfo/FbCVOJopamfkTK2oceCaJOxJUZR25WgNrgut\nzVplp9y0K6Rt7RdsjFpSs3B1MrcGTotPIef4ITi9yBwuIIocs2ubqdi1mOS47K5/\nUUZkNvyKGbbn5DhdSMKEa6stKePEW9ZmdG+ydlKwUi+16KFxElb7I0IHkGvKXO2C\nJlN8lDh3AgMBAAECggEAO7HVaZJ8LZgJXmUMaSBJeXESZ6xfR/OXrxpqdBE6l+Le\n5T61VLRNGKG0scRDte1YuVCGEjU4bbxr59LkVZWOn3nIxHpvB+iPGavZMtM0OkLx\nEqpcws0oaVq7kSOGFjivg3IJdyUigrm5Zsw8DZ4uD19bb3O5ivHJOMPldH+xR5+L\ngdhmLY4KyfV/6pDgvMiDc0en+SneYcTcWyh1zqRDMx3ECcKMQ4iziBWP3gcOrpXY\n8i57E4ZQI1fiWYUEJ88uHyr9EM3WPR90mdzAFmxbtC6CIjj0/p4ArFbvFg82gWsb\nz3e6N/w3vyTRPamvPY6MzM+kJoqwVdXVzaFGWGzsqQKBgQD6y5Wmrh5LFB8XfPT1\n4RxT9I+0rZ4vxl0IYIrv8cQrhuvzjz1WGiHUNegH1TModEPAGpY3rfpisAy3UkzL\n9pijZ3EM3AGJowm9TVVNv4hdy+g0+6KdhdJZOSr8RgwJQ2WEV+zI7+HR6Fdy2kBV\nlbHIeqLvuvJE1Cs5u5xguyjIfQKBgQDhHqdaNJ+JNUCCEN1mwHZQb7psgpwKSmps\nx/zFH8vTIOkOdwCZl0TqHH16ul2cbgrbtuYn5c3T4SNvWDTt1T19oaspkivXNhK2\n34DXtUlLet4TF88lSfnzNe25lQpc5cHYKQD+7RbD9FkdMhavIKptHeJ0wk8OFrSw\nBELb8ZaLAwKBgBcp2H+Vk1yx1hFQTDutd/VVIDS62GJnOs58RDjXJpwykPZk43Bh\nZ4B3HiAjE9+HpX5HtlocKoUU54fDBS7NbtmgwzNB2q6ArXSbgOZ2azzmiWLjXuiX\npI7zFcJJIfF1FRo9GLSSW1QM1o7YE5sUAWCX2xazOI8c3YUui8nvX1vtAoGBAMpP\nsxR1MF6tldCN+XsLQgjdsAsuga8Z23TxcW9yOMn/zJKsTcS6VjuS6Q2viMs5ddap\nE0QN2SEuNpstCTwoJD/QV7NfYrjhJoZkbDTu/fSwcf10qzuWtONmtsLOd2avMLrj\ndrqjNY9a++8qAYrXb3HqpoZJzaQasb1xxuhEwAcjAoGAAQk3xR6ZPqo5cfi46l61\ntEjSOBSRIgF+IAfjZz+y/P7w8moLGEaNIu2K7YXy3wGGAbEz2OkjCDZswL6HrnCy\nx2xoKfmgwRFluJpBkMk7FrvyDsxqUNaJRq3v1K5DRDVYyqUT9F6Rlxb0OIpagArL\nextiIO3GZJ9gionZT486ebc=\n-----END PRIVATE KEY-----\n"
        private_key_id: "f09a5266b63d89ac697969a64fca6c9abb566a16"
        project_id: "maplemonk-prod"
        token_uri: "https://oauth2.googleapis.com/token"
        type: "service_account"
        universe_domain: "googleapis.com"
      location: "US"
      priority: "interactive"
      project: "maplemonk-prod"
      retries: 2
      threads: 8
      method: "service-account-json"
