default:
  target: "dev"
  outputs:
    dev:
      type: "snowflake"
      password: "Maplemonk@123"
      role: "ACCOUNTADMIN"
      database: "DEMO_DB"
      warehouse: "COMPUTE_WH"
      schema: "public"
      threads: 10
      account: "XBA31693.us-east-1"
      user: "Mayank"
      client_session_keep_alive: false
