default:
  target: "dev"
  outputs:
    dev:
      type: "snowflake"
      account: "pm98618.ap-south-1.aws"
      user: "SAI_ABHIJITH707"
      role: "SAI_ABHIJITH707_ROLE"
      database: "SAI_ABHIJITH707_DB"
      warehouse: "COMPUTE_WH"
      schema: "Maplemonk"
      threads: 10
      client_session_keep_alive: false
