default:
  target: "dev"
  outputs:
    dev:
      type: "snowflake"
      account: "jwunsgu-xk39056"
      user: "analyticstbb"
      password: "VVEfimPc1tiHc5I"
      role: "ACCOUNTADMIN"
      database: "tbb_db"
      warehouse: "tbb_wh"
      schema: "maplemonk"
      threads: 10
      client_session_keep_alive: false
