default:
  target: "dev"
  outputs:
    dev:
      type: "snowflake"
      account: "sq89694.ap-south-1.aws"
      user: "Boxseat_ventures_private_Limited931"
      password: "AJMwMAibx0129"
      role: "ACCOUNTADMIN"
      database: "Boxseat_ventures_private_Limited931_DB"
      warehouse: "Boxseat_ventures_private_Limited931_WH"
      schema: "Maplemonk"
      threads: 10
      client_session_keep_alive: false
