default:
  target: "dev"
  outputs:
    dev:
      type: "snowflake"
      account: "kw47569.ap-south-1.aws"
      user: "akash1000"
      password: "Maplemonk@123"
      role: "ACCOUNTADMIN"
      database: "TEST"
      warehouse: "COMPUTE_WH"
      schema: "random"
      threads: 10
      client_session_keep_alive: false
