default:
  target: "dev"
  outputs:
    dev:
      type: "snowflake"
      account: "DW97542.ap-south-1.aws"
      user: "superbottoms"
      password: "Monk@123"
      role: "ACCOUNTADMIN"
      database: "superbottoms_db"
      warehouse: "superbottoms_wh"
      schema: "public"
      threads: 10
      client_session_keep_alive: false
