default:
  target: "dev"
  outputs:
    dev:      
      type: redshift
      host: testcluster.cc20cjjw2d93.ap-south-1.redshift.amazonaws.com
      user: maplemonk
      password: MonkMaple123
      port: 5439
      dbname: dev
      schema: public
      threads: 4
      keepalives_idle: 240 
      connect_timeout: 10 
      ra3_node: true
