default:
  target: "dev"
  outputs:
    dev:
      type: "snowflake"
      account: "pm98618.ap-south-1.aws"
      user: "SASTRY320"
      role: "SASTRY320_ROLE"
      database: "SASTRY320_DB"
      warehouse: "COMPUTE_WH"
      schema: "Maplemonk"
      threads: 10
      client_session_keep_alive: false
