default:
  target: "dev"
  outputs:
    dev:
      type: "snowflake"
      account: "GH49699.ap-south-1.aws"
      user: "analyticsbbk"
      password: "Monk@123"
      role: "ACCOUNTADMIN"
      database: "BBK_DB"
      warehouse: "BBK_WH"
      schema: "Maplemonk"
      threads: 10
      client_session_keep_alive: false
