default:
  target: "dev"
  outputs:
    dev:
      type: "snowflake"
      account: "eh44415.ap-south-1.aws"
      user: "DAPOBER653"
      role: "DAPOBER653_ROLE"
      database: "DAPOBER653_DB"
      warehouse: "COMPUTE_WH"
      schema: "Maplemonk"
      threads: 10
      client_session_keep_alive: false
