{{ config(
            materialized='table',
                post_hook={
                    "sql": "CREATE OR REPLACE TABLE eggozdb.maplemonk.postgre_total_customer AS SELECT u.id as user_id, u.name, u.phone_number, date(u.created_at) as login_date, MIN(o.delivered_at) AS first_order_date, MIN(w.created_at) AS wallet_recharge_date FROM postgres_users u LEFT JOIN postgres_orders o ON u.id = o.user_id LEFT JOIN postgres_wallet w ON u.id = w.user_id WHERE u.is_deleted = FALSE GROUP BY u.id, u.name, u.phone_number, u.created_at; Create or replace table eggozdb.maplemonk.postgre_app_data_overall as SELECT date(COALESCE(o.delivered_at, o.created_at)) AS date, u.id AS user_id, o.id AS order_id, u.name AS name_customer, u.phone_number, p.sku_count, p.short_name, oi.quantity, o.payable_amount, w.id AS wallet_id, w.available_balance, w.total_added_balance, w.total_utilized_balance, w.total_refunded_balance, w.total_bonus_balance, w.created_at AS wallet_recharge_date FROM postgres_order_item oi JOIN postgres_product_city_price pcp ON pcp.id = oi.product_city_id JOIN postgres_product p ON p.id = pcp.product_id JOIN postgres_orders o ON o.id = oi.order_id JOIN postgres_users u ON u.id = o.user_id LEFT JOIN postgres_wallet w ON w.user_id = u.id ORDER BY 1; create or replace table eggozdb.maplemonk.postgre_app_scoiety_data as select date(o.created_at) as date, o.user_id , o.id as order_id , o.payable_amount , s.society_name , p.short_name, date(w.created_at) as wallet_recharge_date from postgres_orders o left join postgres_address a on o.user_id = a.society_id left join postgres_society s on s.id = a.user_id left join postgres_wallet w on w.user_id = o.user_id left join postgres_order_item oi on o.id = oi.order_id left join postgres_product_city_price pcp ON pcp.id = oi.product_city_id left join postgres_product p ON p.id = pcp.product_id; CREATE OR REPLACE TABLE eggozdb.maplemonk.postgre_total_customer1 AS SELECT u.id AS user_id, u.name, u.phone_number, DATE(u.created_at) AS signup_date, fo.first_order_date, fw.wallet_recharge_date FROM postgres_users u LEFT JOIN ( SELECT user_id, MIN(delivered_at) AS first_order_date FROM postgres_orders WHERE delivered_at IS NOT NULL GROUP BY user_id ) fo ON fo.user_id = u.id LEFT JOIN ( SELECT user_id, MIN(created_at) AS wallet_recharge_date FROM postgres_wallet GROUP BY user_id ) fw ON fw.user_id = u.id WHERE u.is_deleted = FALSE; CREATE OR REPLACE TABLE eggozdb.maplemonk.Raw_repeated_Ordered AS SELECT DATE(o.delivered_at) AS date, u.id AS user_id, o.id AS order_id, u.name, u.phone_number, u.email, p.sku_count, p.short_name, SUM(oi.quantity) AS quantity, o.payable_amount AS payable_amount FROM postgres_orders o JOIN postgres_users u ON o.user_id = u.id JOIN postgres_order_item oi ON oi.order_id = o.id JOIN postgres_product_city_price pcp ON pcp.id = oi.product_city_id JOIN postgres_product p ON p.id = pcp.product_id JOIN postgres_retailer r ON r.id = o.retailer_id GROUP BY DATE(o.delivered_at), u.id, o.id, u.name, u.phone_number, u.email, p.sku_count, p.short_name, o.payable_amount;",
                    "transaction": true
                }
            ) }}
            with sample_data as (

                select * from EGGOZDB.MAPLEMONK.Postgres_city
            ),
            
            final as (
                select * from sample_data
            )
            select * from final
            