{{ config(
                        materialized='table',
                            post_hook={
                                "sql": "ALTER TABLE eggozdb.maplemonk.replacement_ageing_noida ADD (ddate Date); UPDATE eggozdb.maplemonk.replacement_ageing_noida SET ddate = TRY_TO_DATE(\"Receiving Date\",\'DD/MM/YYYY\'); ALTER TABLE eggozdb.maplemonk.replacement_ageing_delhi ADD (ddate Date); UPDATE eggozdb.maplemonk.replacement_ageing_delhi SET ddate = TRY_TO_DATE(\"Receiving Date\",\'DD/MM/YYYY\'); ALTER TABLE eggozdb.maplemonk.replacement_ageing_epc_dhankot ADD (ddate Date); UPDATE eggozdb.maplemonk.replacement_ageing_epc_dhankot SET ddate = TRY_TO_DATE(\"Receiving Date\",\'DD/MM/YYYY\'); ALTER TABLE eggozdb.maplemonk.replacement_ageing_bangalore ADD (ddate Date); UPDATE eggozdb.maplemonk.replacement_ageing_bangalore SET ddate = TRY_TO_DATE(\"Receiving Date\",\'DD/MM/YYYY\'); ALTER TABLE eggozdb.maplemonk.replacement_ageing_kolkata ADD (ddate Date); UPDATE eggozdb.maplemonk.replacement_ageing_kolkata SET ddate = TRY_TO_DATE(\"Receiving Date\",\'DD/MM/YYYY\'); ALTER TABLE eggozdb.maplemonk.replacement_ageing_epc_indore ADD (ddate Date); UPDATE eggozdb.maplemonk.replacement_ageing_epc_indore SET ddate = TRY_TO_DATE(\"Receiving Date\",\'DD/MM/YYYY\'); create or replace table eggozdb.maplemonk.replacement_ageing as select region, ddate, classification, total_eggs, ageing, jse_name, case when ageing < 0 then \'-inf-1\' when ageing between 1 and 7 then \'1-7\' when ageing between 8 and 15 then \'8-15\' when ageing between 16 and 21 then \'16-21\' when ageing between 22 and 50 then \'22-50\' when ageing > 50 then \'>50\' else \'null\' end as ageing_range, sum(total_eggs) over (partition by region, classification, year(ddate), month(ddate) order by month(ddate)) total_eggs_monthly_region_classification_wise from ( select \'Noida\' as region, ddate, classification, \"Total Eggs\" as total_eggs, ageing, \"JSE name\" as jse_name from eggozdb.maplemonk.replacement_ageing_noida union all select \'Delhi\' as region, ddate, classification, \"Total Eggs\" as total_eggs, ageing, \"JSE name\" as jse_name from eggozdb.maplemonk.replacement_ageing_delhi union all select \'Gurgaon\' as region, ddate, classification, \"Total Eggs\" as total_eggs, ageing, \"JSE name\" as jse_name from eggozdb.maplemonk.replacement_ageing_epc_dhankot union all select \'Bangalore\' as region, ddate, classification, \"Total Eggs\" as total_eggs, ageing, \"JSE Name\" as jse_name from eggozdb.maplemonk.replacement_ageing_bangalore union all select \'Kolkata\' as region, ddate, classification, \"Total Eggs\" as total_eggs, ageing, \"JSE name\" as jse_name from eggozdb.maplemonk.replacement_ageing_kolkata union all select \'Indore\' as region, ddate, classification, \"Total Eggs\" as total_eggs, ageing, \"JSE name\" as jse_name from eggozdb.maplemonk.replacement_ageing_epc_indore ) where ddate >=\'2023-01-01\' and classification is not null ;",
                                "transaction": true
                            }
                        ) }}
                        with sample_data as (

                            select * from EGGOZDB.MAPLEMONK.Replacement_Ageing_Delhi
                        ),
                        
                        final as (
                            select * from sample_data
                        )
                        select * from final
                        