{{ config(
                        materialized='table',
                            post_hook={
                                "sql": "ALTER TABLE eggozdb.maplemonk.replacement_ageing_noida ADD (ddate Date); UPDATE eggozdb.maplemonk.replacement_ageing_noida SET ddate = TRY_TO_DATE(\"Receiving Date\",\'DD/MM/YYYY\'); ALTER TABLE eggozdb.maplemonk.replacement_ageing_delhi ADD (ddate Date); UPDATE eggozdb.maplemonk.replacement_ageing_delhi SET ddate = TRY_TO_DATE(\"Receiving Date\",\'DD/MM/YYYY\'); ALTER TABLE eggozdb.maplemonk.replacement_ageing_gurgaon ADD (ddate Date); UPDATE eggozdb.maplemonk.replacement_ageing_gurgaon SET ddate = TRY_TO_DATE(\"Receiving Date\",\'DD/MM/YYYY\'); ALTER TABLE eggozdb.maplemonk.replacement_ageing_bangalore ADD (ddate Date); UPDATE eggozdb.maplemonk.replacement_ageing_bangalore SET ddate = TRY_TO_DATE(\"Receiving Date\",\'DD/MM/YYYY\'); ALTER TABLE eggozdb.maplemonk.replacement_ageing_kolkata ADD (ddate Date); UPDATE eggozdb.maplemonk.replacement_ageing_kolkata SET ddate = TRY_TO_DATE(\"Receiving Date\",\'DD/MM/YYYY\'); create or replace table eggozdb.maplemonk.replacement_ageing_consolidated_mtd as select \'Noida-GT\' as area, \"JSE name\", sum(\"Total Eggs\"*\"AGEING\")/sum(\"AGEING\") as ageing from eggozdb.maplemonk.replacement_ageing_noida where \"DDATE\" between TO_DATE(DATE_TRUNC(\'month\', cast(timestampadd(minute,660,current_date()) as date))) AND cast(timestampadd(minute, 660, getdate()) as date) and \"Stock date/Packet date\" is not null group by \"JSE name\" union all select \'Delhi-GT\' as area, \"JSE name\", sum(\"Total Eggs\"*\"AGEING\")/sum(\"AGEING\") as ageing from eggozdb.maplemonk.replacement_ageing_delhi where \"DDATE\" between TO_DATE(DATE_TRUNC(\'month\', cast(timestampadd(minute,660,current_date()) as date))) AND cast(timestampadd(minute, 660, getdate()) as date) and \"Stock date\" is not null group by \"JSE name\" union all select \'Gurgaon-GT\' as area, \"JSE name\", sum(\"Total Eggs\"*\"AGEING\")/sum(\"AGEING\") as ageing from eggozdb.maplemonk.replacement_ageing_gurgaon where \"DDATE\" between TO_DATE(DATE_TRUNC(\'month\', cast(timestampadd(minute,660,current_date()) as date))) AND cast(timestampadd(minute, 660, getdate()) as date) and \"Stock date\" is not null group by \"JSE name\" union all select \'Bangalore-GT\' as area, \"JSE Name\", sum(\"Total Eggs\"*\"AGEING\")/sum(\"AGEING\") as ageing from eggozdb.maplemonk.replacement_ageing_bangalore where \"DDATE\" between TO_DATE(DATE_TRUNC(\'month\', cast(timestampadd(minute,660,current_date()) as date))) AND cast(timestampadd(minute, 660, getdate()) as date) and \"Stock date\" is not null group by \"JSE Name\" union all select \'Kolkata-GT\' as area, \"JSE name\", sum(\"Total Eggs\"*\"AGEING\")/sum(\"AGEING\") as ageing from eggozdb.maplemonk.replacement_ageing_kolkata where \"DDATE\" between TO_DATE(DATE_TRUNC(\'month\', cast(timestampadd(minute,660,current_date()) as date))) AND cast(timestampadd(minute, 660, getdate()) as date) and \"Stock date\" is not null group by \"JSE name\";",
                                "transaction": true
                            }
                        ) }}
                        with sample_data as (

                            select * from EGGOZDB.MAPLEMONK.Replacement_Ageing_Noida
                        ),
                        
                        final as (
                            select * from sample_data
                        )
                        select * from final
                        